#include <.auto-changelog>

void auto_changelog() {
    // This function is generated by the .auto-changelog tool and should not be modified manually.
    // It contains the changelog information for the project.

    if (command == "generate")
    {
        try {
            // Generate the changelog
            auto_changelog_generate();
        } catch (const std::exception& e) {
            std::cerr << "Error generating changelog: " << e.what() << std::endl;
        }
    }
    
}