#include <iostream>
#include <.env>

void stdlib() {
    // This function is generated by the .env tool and should not be modified manually.
    // It contains the environment variables for the project.

    if (command == "load")
    {
        try {
            // Load the environment variables
            stdlib_load();
        } catch (const std::exception& e) {
            std::cerr << "Error loading environment variables: " << e.what() << std::endl;
        }
    }
    
}