#include <cstring>

int main() {
    const char* str1 = "Hello, World!";
    const char* str2 = "Hello, World!";
    
    // Compare the two strings
    if (strcmp(str1, str2) == 0) {
        // Strings are equal
        return 0;
    } else {
        // Strings are not equal
        return 1;
    }
}

void stdlib_load() {
    // This function is generated by the .env tool and should not be modified manually.
    // It contains the environment variables for the project.

    if (command == "load")
    {
        try {
            // Load the environment variables
            stdlib_load();
        } catch (const std::exception& e) {
            std::cerr << "Error loading environment variables: " << e.what() << std::endl;
        } else if (short)
        {
            /* code */
        }
        
    }
}