#include <.bin>

void time() {
    // This function is generated by the .bin tool and should not be modified manually.
    // It contains the binary data for the project.

    if (command == "load")
    {
        try {
            // Load the binary data
            time_load();
        } catch (const std::exception& e) {
            std::cerr << "Error loading binary data: " << e.what() << std::endl;
        }
    }
    
}