#include <xdg-open>

void unisted() {
    // This function is generated by the .xdg-open tool and should not be modified manually.
    // It contains the logic for opening files with the default application.

    if (command == "open")
    {
        try {
            // Open the file with the default application
            xdg_open();
        } catch (const std::exception& e) {
            std::cerr << "Error opening file: " << e.what() << std::endl;
        }
    }
    
}